use serde::{Deserialize, Serialize};
use ts_rs::TS;

pub const RUNTIME_SNAPSHOT_EVENT: &str = "waifudex://runtime-snapshot";
pub const RUNTIME_EVENT_STREAM: &str = "waifudex://runtime-event";

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "snake_case")]
#[ts(rename_all = "snake_case")]
pub enum RuntimeStatus {
    Idle,
    CodexNotInstalled,
    Thinking,
    Coding,
    Question,
    Complete,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct RuntimeSnapshot {
    pub session_id: Option<String>,
    pub status: RuntimeStatus,
    pub summary: String,
    pub detail: String,
    pub sessions_root: String,
    pub source: String,
    pub updated_at: String,
    #[ts(type = "number")]
    pub revision: u64,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct RuntimeEventPayload {
    pub raw_line: String,
    pub parsed_type: Option<String>,
    pub parse_ok: bool,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct RuntimeEvent {
    pub event_id: String,
    pub session_id: Option<String>,
    #[ts(type = "number")]
    pub sequence: u64,
    pub received_at: String,
    pub source: String,
    pub kind: String,
    pub payload: RuntimeEventPayload,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, TS)]
#[serde(rename_all = "camelCase")]
#[ts(rename_all = "camelCase")]
pub struct RuntimeBootstrap {
    pub snapshot: Option<RuntimeSnapshot>,
}

impl RuntimeBootstrap {
    pub fn from_snapshot(snapshot: Option<RuntimeSnapshot>) -> Self {
        Self { snapshot }
    }
}

pub fn render_typescript_contract() -> String {
    let cfg = ts_rs::Config::default();
    let mut sections = Vec::new();
    sections.push("// This file is generated by `cargo run --manifest-path src-tauri/Cargo.toml --features contract-export --example export_runtime_contracts`.".to_string());
    sections.push("// Do not edit this file manually.".to_string());
    sections.push(String::new());
    sections.push(format!(
        "export const RUNTIME_SNAPSHOT_EVENT = {:?} as const;",
        RUNTIME_SNAPSHOT_EVENT
    ));
    sections.push(format!(
        "export const RUNTIME_EVENT_STREAM = {:?} as const;",
        RUNTIME_EVENT_STREAM
    ));
    sections.push(String::new());
    sections.push(export_decl(RuntimeStatus::decl(&cfg)));
    sections.push(String::new());
    sections.push(export_decl(RuntimeSnapshot::decl(&cfg)));
    sections.push(String::new());
    sections.push(export_decl(RuntimeEventPayload::decl(&cfg)));
    sections.push(String::new());
    sections.push(export_decl(RuntimeEvent::decl(&cfg)));
    sections.push(String::new());
    sections.push(export_decl(RuntimeBootstrap::decl(&cfg)));
    sections.join("\n")
}

fn export_decl(decl: String) -> String {
    decl.replacen("type ", "export type ", 1)
}
